# Generated by Django 5.2.6 on 2025-11-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-start_date']},
        ),
    ]
